version: '3.7'
services:
  app:
    depends_on:
      - postgres
    build: .
    container_name: nest_pg
    restart: always
    ports:
      - 3000
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db_test
      VIRTUAL_HOST: api.alejandrogalaz.space
      LETSENCRYPT_HOST: api.alejandrogalaz.space
    networks:
      - default
      - internal

  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data_app:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data_app:

networks:
  default:
    external: true
    name: npm
  internal:
    internal: true
