version: '3'

services:
  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: nest-pg-dev
    container_name: nest_pg_dev
    restart: always
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      NODE_ENV: dev
      PORT: ${PORT}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
    command: yarn start:dev
    # debug
    # command: yarn start:debug:docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  postgres:
    image: postgres:13
    container_name: postgres_db_dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres_data_app_dev:/var/lib/postgresql/data

volumes:
  postgres_data_app_dev:
