version: '3'

services:
  pokedexapp:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: nest-pokemon-api-dev
    container_name: nest_pokemon_api_dev
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: dev
      DB_HOST: mongo
      DB_PORT: 27017
      PORT: 3000
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:5.0
    container_name: mongo_db_pokemon_dev
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express_pokemon_dev
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8099:8081

volumes:
  mongodb_data:
