version: '3.7'
services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    image: nest-pg
    container_name: nest_pg
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME

  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - postgres_data_app:/var/lib/postgresql/data

volumes:
  postgres_data_app:
