name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: Push image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: run docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            docker compose down
            docker rmi -f $(docker images -q)
            docker compose pull
            docker compose up -d
