name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: Push image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: Stop and remove existing postgres_db container
        run: |
          docker stop postgres_db || true
          docker rm postgres_db || true
      - name: Stop and remove existing nest_pg container
        run: |
          docker stop nest_pg || true
          docker rm nest_pg || true
      - name: Run Docker container db
        run: |
          docker run -d \
            --name postgres_db \
            -e POSTGRES_DB=${{secrets.DB_NAME}} \
            -e POSTGRES_USER=${{secrets.DB_USER}} \
            -e POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}} \
            -v postgres_data_app:/var/lib/postgresql/data \
            postgres:13
      - name: Run Docker container app
        run: |
          docker run -d \
            --name nest_pg \
            --restart always \
            -e PORT=3000 \
            -e DB_HOST=postgres_db \
            -e DB_PORT=5432 \
            -e DB_USER=${{secrets.DB_USER}} \
            -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
            -e DB_NAME=${{secrets.DB_NAME}} \
            --network npm \
            alejandrogalaz21/test:latest
