name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u alejandrogalaz21 -p dckr_pat_QXhZRv3XA02Io51Gj3vPmdIUcIg
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alejandrogalaz21/nest-pg:latest
    - name: Push image
      run: docker push alejandrogalaz21/nest-pg:latest
