name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: Push image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/test:latest
      - name: run docker container db
        run: docker run -d \
          --name postgres_db \
          -p 5432:5432 \
          -e POSTGRES_DB=${{secrets.DB_NAME}} \
          -e POSTGRES_USER=${{secrets.DB_USER}} \
          -e POSTGRES_PASSWORD=${{secrets.DB_PASSWORD}} \
          -v postgres_data_app:/var/lib/postgresql/data \
          --network internal \
          postgres:13
      - name: run docker container app
        run: docker run -d \
          --name nest_pg \
          --restart always \
          -p 3000:3000 \
          -e PORT=3000 \
          -e DB_HOST=postgres \
          -e DB_PORT=5432 \
          -e DB_USER=${{secrets.DB_USER}} \
          -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
          -e DB_NAME=${{secrets.DB_NAME}} \
          --network npm \
          --network internal \
          alejandrogalaz21/test:latest
